Sm2+fastecdlp
secretflow/yacl pull request #348
Opened 2024-06-26 09:18 UTC by ShallMate

2024-06-26 09:19 UTC, ShallMate commented
I have read the CLA Document and I hereby sign the CLA

2024-07-01 03:10 UTC, Jamie-Cui approved these changes
剩下的我没有大问题了，后续可能我们也会在内部对这部分代码进行一些修改，感谢贡献 @ShallMate

2024-07-01 05:58 UTC, Jamie-Cui requested changes

2024-07-01 05:58 UTC, Jamie-Cui commented on examples/HESM2/README.md
> +本代码是SM2加法同态加密 ([密码学报 2022](http://www.jcr.cacrnet.org.cn/CN/10.13868/j.cnki.jcr.000532)) 结合FastECDLP([IEEE TIFS 2023](https://ieeexplore.ieee.org/document/10145804))。
建议在这里补充说明一下，该方案并不是标准 SM2 实现

2024-07-01 05:58 UTC, Jamie-Cui commented on examples/HESM2/ahesm2.h
> +
这里添加一下 `namespace examples::hesm2 {}`

2024-07-01 05:58 UTC, Jamie-Cui commented on examples/HESM2/config.h
> +extern int Ilen;
这里可以直接使用 `constexpr` 定义这些参数，直接定义在 header 里面就好了

2024-07-01 06:56 UTC, Jamie-Cui requested changes

2024-07-01 06:56 UTC, Jamie-Cui commented on examples/HESM2/README.md
> +#include "private_key.h"
```cpp
#include "examples/HESM2/private_key.h"
#include "examples/HESM2/ahesm2.h"
#include "examples/HESM2/config.h"
```

2024-07-01 06:56 UTC, Jamie-Cui commented on examples/HESM2/ahesm2.cc
> +  const auto& ec_group = pk.GetEcGroup();
感觉可以在 Encrypt 之前 `YACL_ENFORCE()` 一下 message 的大小不要超过设定的 size

2024-07-02 10:01 UTC, ShallMate commented
我把文件夹的名字从大写改为了小写（与其他example保持一致），其余部分已经按您的要求进行了修改哈～。 @Jamie-Cui

2024-07-02 11:07 UTC, Jamie-Cui commented on examples/hesm2/ahesm2.cc
> +  auto generator = (*ec_group).GetGenerator();
这里 `ec_group->GetGenerator()` 就可以～

2024-07-02 11:08 UTC, Jamie-Cui commented on examples/hesm2/t2.h
> +
添加 `namespace examples::hesm2{}`

2024-07-02 11:09 UTC, Jamie-Cui commented on examples/hesm2/t1.h
> +
添加 `namespace examples::hesm2{}`

2024-07-03 03:22 UTC, Jamie-Cui commented on examples/hesm2/public_key.h
> +      : point_(std::move(point)), ec_group_(std::move(ec_group)) {}
这里 pointer 可以不使用 std::move

2024-07-03 03:26 UTC, Jamie-Cui commented on examples/hesm2/private_key.h
> +
namespace

2024-07-03 03:26 UTC, Jamie-Cui commented on examples/hesm2/public_key.h
> +
namespace

2024-07-03 10:25 UTC, ShallMate commented on examples/hesm2/t1.h
> +class HashMapT1 {
之前由于yacl里面没有k-v形式的cuckoo，于是我使用的hashmap的T1，后面我自己实现了改进版的cuckoo hashing后我保留了关于hashmap的实现，现在我把它删掉了。

2024-07-04 03:25 UTC, Jamie-Cui commented
我这边没有其他问题了，看 @shaojian-ant 那边 ok 的话就可以和入了

2024-07-04 03:28 UTC, shaojian-ant commented
LGTM

2024-07-04 03:30 UTC, shaojian-ant approved these changes
LGTM

2024-07-04 03:34 UTC, Jamie-Cui approved these changes
感谢 @ShallMate 的贡献，稍等这个 PR 我们会合入，再次感谢

2024-07-04 05:53 UTC, merged