modify revise
secretflow/yacl pull request #35
Opened 2023-03-04 10:51 UTC by zr-182

2023-03-04 10:52 UTC, zr-182 commented
您发给我的邮件已经收到。This is an automatic reply, confirming that your e-mail was received.Thank you

2023-03-04 11:00 UTC, zr-182 commented
I have read the CLA Document and I hereby sign the CLA

2023-03-04 11:02 UTC, zr-182 commented
I have read the CLA Document and I hereby sign the CLA

2023-03-04 11:03 UTC, zr-182 commented
recheck

2023-03-04 11:06 UTC, zr-182 commented
> 

recheck

2023-03-04 11:14 UTC, zr-182 commented
recheck

2023-03-04 11:30 UTC, zr-182 commented
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/secretflow/.github/blob/main/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> _**I have read the CLA Document and I hereby sign the CLA**_
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

recheck

2023-03-04 12:49 UTC, zr-182 reviewed
recheck

2023-03-04 14:06 UTC, 6fj requested changes

2023-03-04 14:06 UTC, 6fj commented on README.md
> +YACL (Yet Another Crypto library) is a C++ library that contains modules and utilities which other SecretFlow codes depend on.
I don't think "codes" is correct here.

e.g. we usually say "other peoples' code" instead of "other peoples' codes".

2023-03-04 14:06 UTC, 6fj commented on REPO_LAYOUT.md
> +  - [tools/](yacl/crypto/tools/): Theoretical cryptographic tools such as Random Oracle (RO), Pseudo-Random Generator (PRG).
Pseudorandom Generator is correct.

2023-03-04 14:06 UTC, 6fj commented on yacl/base/int128.h
> +  // width is an implementation defined behavior if the source value would not fit
s/implementation defined/implementation-defined

2023-03-04 14:06 UTC, 6fj commented on yacl/crypto/base/hash/hash_interface.h
> +// method to get a hash of all data added to the object from its creation or
since is good to go.

2023-03-04 14:07 UTC, 6fj commented
recheck

2023-03-04 14:11 UTC, 6fj commented
Hi @zr-182 ,

I find the changes are committed by @IIIImp . Please double-check your git settings.
Thanks.

2023-03-05 06:59 UTC, zr-182 commented
Hi @6fj ,

I added new commits under your advice . Please check if they r OK . 

And , as you said , the first commit is from @IIIImp . I forgot to change the git account but now I have changed it. I wonder if it is all right.

2023-03-07 09:50 UTC, IIIImp commented
I have read the CLA Document and I hereby sign the CLA

2023-03-07 09:55 UTC, zr-182 commented
recheck

2023-03-10 02:17 UTC, merged