【OSCP】 + 在 YACL 上实现对称可搜索加密算法
secretflow/yacl pull request #423
Opened 2024-11-30 04:59 UTC by xbw886

Fixed + https://github.com/secretflow/yacl/issues/97

2024-11-30 08:19 UTC, Jamie-Cui commented
Hi, 因为现在价格有些变化，可否将 SSE 的实现代码放到 yacl/examples 文件夹下？感谢参与

2024-12-03 13:56 UTC, Jamie-Cui requested changes

2024-12-03 13:56 UTC, Jamie-Cui commented on yacl/examples/primitives/sse/BUILD.bazel
> +# Copyright 2024 Ant Group Co., Ltd.
这里的 license 可以改成你自己的名字，不需要有 Ant Group

2024-12-03 13:56 UTC, Jamie-Cui commented on yacl/examples/primitives/sse/BUILD.bazel
> +    name = "TSet",
建议文件名、bazel target 名称小写

2024-12-03 13:56 UTC, Jamie-Cui commented on yacl/examples/primitives/sse/TSet.cc
> +namespace yacl::examples::primitives::sse {
P2（仅建议可不修改）：可以只使用两层的 namespace 即可

2024-12-03 13:56 UTC, Jamie-Cui commented on yacl/examples/primitives/sse/TSet.h
> +  bool areVectorsEqual(const std::vector<uint8_t>& vec1,
yacl 的函数名需要驼峰（大写字母开头）

2024-12-03 13:56 UTC, Jamie-Cui commented on yacl/examples/primitives/sse/TSet.h
> +  std::vector<std::set<int>> Free_;
变量名需要统一小写

2024-12-03 13:56 UTC, Jamie-Cui commented on yacl/examples/primitives/sse/sse.h
> +class SSE {
建议命名为 `Sse`

2024-12-03 13:56 UTC, Jamie-Cui commented on yacl/examples/primitives/sse/sse.h
> +          "/home/xbw/yacl/yacl/examples/primitives/sse/test.csv");
这里的 data 文件需要进行路径修改，可以参考 psi 里面获取 test data 路径的方式

2024-12-03 13:57 UTC, Jamie-Cui commented
以及，建议放在 `yacl/examples/sse/` 目录下即可，不需要保留 `primitives/` 文件夹

2024-12-10 10:30 UTC, Jamie-Cui commented
Hello，UT 依然是失败的状态，麻烦先 fix 一下

2024-12-10 12:05 UTC, xbw886 commented
[macOS_ut_arm64]这个UT中的错误貌似没有出在我贡献的代码中
//yacl/link:factory_test                                                 FAILED in 0.1s
  /private/var/tmp/_bazel_distiller/bedaa68a8664d1b29e96b826d058247f/execroot/_main/bazel-out/darwin_arm64-opt/testlogs/yacl/link/factory_test/test.log

2025-02-04 10:35 UTC, xbw886 commented
hello，麻烦处理下这个pr，谢谢

2025-02-06 02:56 UTC, changtong9 commented on yacl/examples/sse/sse.cc
> +      std::vector<uint8_t> e = AesCtrEncrypt(ind_vector, Ke, 0);
IV值使用随机数

2025-02-06 03:01 UTC, changtong9 commented on yacl/examples/sse/sse.cc
> +  k_map_["Ks"] = "This is Ks";
使用随机数？

2025-02-06 03:07 UTC, changtong9 commented on yacl/examples/sse/tset.cc
> +    const auto& t = T.at(keyword);  // 使用 at 方法访问元素
可能会抛异常，使用find方法?

2025-02-07 06:39 UTC, changtong9 commented on yacl/examples/sse/sse.h
> +  std::pair<std::vector<std::vector<TSet::Record>>, std::string> EDBSetup(
最外层接口尽量简洁一点，感觉可以在 EDBSetup 里生成 iv 保存在成员变量中，不用从外部传。

2025-02-07 06:39 UTC, changtong9 commented on yacl/examples/sse/sse.h
>    std::vector<std::string> SearchProtocol(
同上

2025-02-07 07:09 UTC, changtong9 commented on yacl/examples/sse/sse.cc
> +  iv_ = yacl::crypto::RandU32();
初始化了两次？

2025-02-07 07:09 UTC, changtong9 commented on yacl/examples/sse/sse.cc
> +void Sse::ProcessAndUpdateTAndXSet(const uint128_t& iv_) {
不用传了吧，直接用成员变量？

2025-02-07 07:33 UTC, changtong9 commented
LGTM

2025-02-07 10:08 UTC, rivertalk commented on yacl/examples/sse/sse_test.cc
> +    // 初始化SSE系统，使用默认参数
Please do not use 中文 for comments

PS: The code is self-explained, no need to comment here :P

2025-02-10 07:39 UTC, warriorpaw requested changes
1、增加一个yacl/examples/sse/README文件，简单描述新增的算法，并注明算法来源
参考
https://github.com/secretflow/secretflow/blob/d760429d8ab34cc4dcc45d4c7a5beab76c7edd36/examples/security/h_bd/README.md

2、为新增的类和方法增加注释，描述类和方法的作用；为代码实现增加注释
参考
https://github.com/secretflow/yacl/blob/5b1ecae2b15f43d9c5f4068019ac92bf505411f9/yacl/crypto/rand/rand.h


注释和文档请使用英文

2025-02-10 07:39 UTC, warriorpaw commented on yacl/examples/sse/sse.cc
> +      std::vector<uint8_t> e = AesCtrEncrypt(ind_vector, Ke, iv_);
不要反复使用同一组key/iv加密不同的数据

2025-02-10 07:39 UTC, warriorpaw commented on yacl/examples/sse/tset.cc
> +        goto restart;
不要使用goto，用while/for等替代掉

2025-02-10 07:39 UTC, warriorpaw commented on yacl/examples/sse/tset.cc
> +  return {tset_, Kt};
为什么 sse / tset两个类的一些函数要把私有成员变量copy一份返回出去？

如果外部有访问私有成员的需求，麻烦用 T& GetSomething() 或 const T& GetSomething() const 接口替代

2025-02-10 07:39 UTC, warriorpaw commented on yacl/examples/sse/sse.cc
> +    T_[keyword] = t;
避免不必要的copy，std map/set/vector在插入新值时，如果可以 请使用 emplace(std::move(..), ..)
比如这里，用 T_.emplace(keyword, std::move(t))

2025-02-17 02:46 UTC, warriorpaw requested changes

2025-02-17 02:46 UTC, warriorpaw commented on yacl/examples/sse/tset.cc
> +          value_xor_k[k] = beta_si[k] ^ K[k % K.size()];
![image](https://github.com/user-attachments/assets/91671d98-6d05-451c-b50b-01b304c9683b)
![image](https://github.com/user-attachments/assets/d21a84b9-409b-40e1-ab80-b02301d4d8b7)
原论文中，H派生的K长度和beta_si一致的，但是这里的实现是生成一个短于beta_si的K循环xor。

和上面aes反复使用同一个key/iv一样，最基本的密码安全都违反了。请按照论文实现。

2025-02-17 09:22 UTC, warriorpaw requested changes

2025-02-17 09:22 UTC, warriorpaw commented on yacl/examples/sse/sse.cc
> +  auto rand_bytes_Ks = yacl::crypto::RandU32();
![image](https://github.com/user-attachments/assets/47092191-687d-47e0-bcc5-5b8a1b42980b)

论文中对F的定义，输入的K长度要达到安全系数λ，这里只用32bits和论文内容不符

2025-02-19 11:42 UTC, changtong9 commented on yacl/examples/sse/sse.cc
> +  const auto& curve = yacl::crypto::GetCurveMetaByName("secp224r1");
改成secp256r1

2025-02-19 12:04 UTC, changtong9 commented on yacl/examples/sse/tset.cc
> +          K.insert(K.end(), hash_part.begin(), hash_part.end());
K 的长度为 n(λ)+1，参考论文第六章

2025-03-04 07:15 UTC, changtong9 commented on yacl/examples/sse/tset.cc
> +          hash_value = (hash_value * 256 + hash[i]) % b_;
不要使用 magic number，可以用 constexpr int xxx = 10，通过变量名表示常量含义。

2025-03-04 07:16 UTC, changtong9 commented on yacl/examples/sse/tset.cc
> +        size_t num_sha256 = (beta_si.size() + 31) / 32;
同上

2025-03-04 07:16 UTC, rivertalk commented
/gemini review

2025-03-04 07:23 UTC, rivertalk commented
@gemini-code-assist

2025-03-04 07:28 UTC, rivertalk commented
/gemini review

2025-03-04 08:04 UTC, changtong9 commented on yacl/examples/sse/sse.cc
> +      __uint128_t iv = yacl::crypto::RandU128();
使用 YACL 的 uint128_t

2025-03-04 08:09 UTC, changtong9 commented
把代码放在 `yacl/crypto/experimental/sse`目录吧

2025-03-05 02:25 UTC, changtong9 commented on yacl/crypto/experimental/sse/sse.cc
> +  constexpr int DECIMAL_BASE = 10;
一般写为kDecimalBase，k前缀+驼峰式命名，可以参考库里类似的用法

2025-03-05 11:50 UTC, warriorpaw approved these changes
LGTM

2025-03-06 02:05 UTC, changtong9 commented
LGTM

2025-03-07 09:02 UTC, deadlywing approved these changes

2025-03-08 07:19 UTC, rivertalk approved these changes

2025-03-08 07:21 UTC, merged